<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>disable</Nullable>
    <RootNamespace>Tosox.MagRetentionReload.Net</RootNamespace>
    <AssemblyName>Tosox.MagRetentionReload.Net</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Configurations>Debug;Release</Configurations>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\MagRetentionReload\ModInfo.cs" Link="ModInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Fika.Core" HintPath="..\References\Fika.Core.dll" Private="false" />
  </ItemGroup>
</Project>
